mm_list = ['an elephant',
           'the Apollo lunar module',
           'an oak tree',
           'a blue whale',
           'the average U.S. house',
           'the Statue of Liberty',
           'an old redwood tree',
           'a football field',
           'Boeing 747',
           'Saturn V rocket',
           'the Gateway arch',
           'Titanic',
           'Hoover Dam',
           'the Great Pyramid of Giza',
           'Boeing Everett Factory',
           'Vatican city',
           'Large Hadron collider',
           'Deimos',
           'Mount Everest',
           'Rhode Island',
           'West Virginia',
           'Grand Canyon',
           'Texas',
           'the Moon',
           'Sirius B',
           'the Minecraft world',
           'Uranus',
           'Arcturus',
           'Aldebaran',
           'the distance from Voyager 1 to Earth']
pp_list = ['centimeter',
           'millimeter',
           'a matchstick',
           'a sunflower seed',
           'the grain of rice',
           'ant',
           'ant mouth',
           'pencil lead',
           'a duckweed',
           'LCD pixel',
           'micron',
           'amoeba',
           'a mist droplet',
           'a skin cell',
           'a bacteriophage',
           'the red light wavelength',
           'the ultraviolet wavelength',
           'the smallest thing visible to an optical microscope',
           'the DNA molecule',
           'transistor gate',
           'a phospholipid',
           'the X-ray wavelength',
           'the smallest thing visible to an electron microscope',
           'the shortest length ever confirmed',
           'a quark',
           'the Plank length']
